name: 'Static Analysis'
description: 'Run static analysis'
inputs:
  checkov_version:
    description: 'Checkov version'
    default: "2.3.245"
  tfsec_version:
    description: 'tfsec version'
    default: "1.28.1"

runs:
  using: "composite"

  steps:
  - name: Test with Checkov
    id: checkov
    uses: bridgecrewio/checkov-action@v12.1346.0
    with:
      framework: terraform
      soft_fail: true
      output_format: sarif
      output_file_path: sarif_dir
      version: ${{ inputs.checkov_version}}
  - name: tfsec
    uses: aquasecurity/tfsec-sarif-action@v0.1.4
    with:
      tfsec_version: ${{ inputs.tfsec_version }}
      soft_fail: true
      sarif_file: tfsec.sarif


