on: [push]

# permission can be added at job level or workflow level    
permissions: write-all
# id-token: write # This is required for requesting the JWT
# contents: read # This is required for actions/checkout
# pull-requests: write # todo czy to jest ptorzebne?
# actions: read


jobs:
  static-analysis:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
    - uses: actions/checkout@v3
    - id: foo
      uses: ./.github/actions/lint
      with:
        terraform-directory: '.'
